export interface Recipe {
  id: number;
  name: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  prepTime: number; // minutes
  difficulty: '简单' | '中等' | '困难';
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  ingredients: string[];
  steps: string[];
  tags: string[];
}

export const recipes: Recipe[] = [
  {
    id: 1,
    name: '鸡胸肉沙拉',
    description: '高蛋白低脂肪的完美减脂餐，搭配新鲜蔬菜，营养均衡',
    calories: 285,
    protein: 35,
    carbs: 15,
    fat: 9,
    prepTime: 15,
    difficulty: '简单',
    mealType: 'lunch',
    ingredients: [
      '鸡胸肉 150g',
      '生菜 100g',
      '小番茄 50g',
      '黄瓜 50g',
      '橄榄油 1勺',
      '柠檬汁 适量',
      '黑胡椒 适量',
      '盐 适量',
    ],
    steps: [
      '鸡胸肉加盐和黑胡椒腌制10分钟',
      '平底锅少油煎至两面金黄，切片',
      '蔬菜洗净切好，摆盘',
      '放上鸡胸肉片，淋橄榄油和柠檬汁',
    ],
    tags: ['减脂', '高蛋白', '低卡'],
  },
  {
    id: 2,
    name: '燕麦水果早餐',
    description: '富含纤维的燕麦搭配新鲜水果，开启元气满满的一天',
    calories: 320,
    protein: 10,
    carbs: 55,
    fat: 8,
    prepTime: 10,
    difficulty: '简单',
    mealType: 'breakfast',
    ingredients: [
      '燕麦片 50g',
      '脱脂牛奶 200ml',
      '香蕉 半根',
      '蓝莓 30g',
      '蜂蜜 1小勺',
      '坚果碎 10g',
    ],
    steps: [
      '燕麦片用牛奶浸泡5分钟',
      '香蕉切片，蓝莓洗净',
      '将水果铺在燕麦上',
      '淋上蜂蜜，撒坚果碎即可',
    ],
    tags: ['早餐', '高纤维', '快手'],
  },
  {
    id: 3,
    name: '清蒸鲈鱼',
    description: '鲜嫩清蒸，保留鱼肉原味，低脂高蛋白',
    calories: 220,
    protein: 32,
    carbs: 3,
    fat: 8,
    prepTime: 25,
    difficulty: '中等',
    mealType: 'dinner',
    ingredients: [
      '鲈鱼 1条（约300g）',
      '姜 适量',
      '葱 2根',
      '蒸鱼豉油 2勺',
      '料酒 1勺',
      '盐 少许',
    ],
    steps: [
      '鲈鱼洗净，两面划几刀，抹盐和料酒',
      '姜切片，葱切段，铺在鱼身和盘底',
      '水开后上锅蒸8-10分钟',
      '倒掉蒸出来的水，淋上蒸鱼豉油',
      '热油浇在鱼身上即可',
    ],
    tags: ['低脂', '高蛋白', '晚餐'],
  },
  {
    id: 4,
    name: '番茄鸡蛋荞麦面',
    description: '经典番茄鸡蛋搭配健康荞麦面，低GI更饱腹',
    calories: 380,
    protein: 18,
    carbs: 52,
    fat: 10,
    prepTime: 20,
    difficulty: '简单',
    mealType: 'lunch',
    ingredients: [
      '荞麦面 80g',
      '番茄 2个',
      '鸡蛋 2个',
      '葱花 适量',
      '盐 适量',
      '食用油 1勺',
    ],
    steps: [
      '番茄切块，鸡蛋打散',
      '荞麦面煮熟过凉水',
      '炒鸡蛋盛出，炒番茄至出汁',
      '加入鸡蛋和面条翻炒均匀',
      '加盐调味，撒葱花出锅',
    ],
    tags: ['午餐', '低GI', '家常'],
  },
  {
    id: 5,
    name: '西兰花炒虾仁',
    description: '高蛋白低卡路里的完美组合，营养又美味',
    calories: 210,
    protein: 28,
    carbs: 8,
    fat: 7,
    prepTime: 15,
    difficulty: '简单',
    mealType: 'dinner',
    ingredients: [
      '虾仁 150g',
      '西兰花 200g',
      '蒜 3瓣',
      '料酒 1勺',
      '盐 适量',
      '食用油 1勺',
    ],
    steps: [
      '虾仁用料酒腌制5分钟',
      '西兰花焯水1分钟捞出',
      '热油爆香蒜末',
      '加入虾仁翻炒至变色',
      '加入西兰花，调味翻炒均匀',
    ],
    tags: ['低卡', '高蛋白', '快手'],
  },
  {
    id: 6,
    name: '豆腐蔬菜汤',
    description: '温暖低卡的蔬菜豆腐汤，适合晚餐轻食',
    calories: 150,
    protein: 12,
    carbs: 10,
    fat: 6,
    prepTime: 20,
    difficulty: '简单',
    mealType: 'dinner',
    ingredients: [
      '嫩豆腐 200g',
      '白菜 100g',
      '胡萝卜 50g',
      '香菇 3朵',
      '姜 2片',
      '盐 适量',
      '香油 少许',
    ],
    steps: [
      '蔬菜洗净切块，豆腐切块',
      '锅中加水烧开，放入姜片和胡萝卜',
      '加入香菇和白菜煮5分钟',
      '加入豆腐再煮3分钟',
      '加盐调味，淋香油出锅',
    ],
    tags: ['低卡', '素食', '晚餐'],
  },
  {
    id: 7,
    name: '全麦三明治',
    description: '营养全面的快手早餐，搭配鸡蛋和蔬菜',
    calories: 350,
    protein: 20,
    carbs: 42,
    fat: 12,
    prepTime: 10,
    difficulty: '简单',
    mealType: 'breakfast',
    ingredients: [
      '全麦面包 2片',
      '鸡蛋 1个',
      '生菜 2片',
      '番茄 2片',
      '火腿 1片',
      '低脂沙拉酱 少许',
    ],
    steps: [
      '鸡蛋煎熟',
      '面包片烤至微黄',
      '依次铺上生菜、番茄、火腿、鸡蛋',
      '挤少许沙拉酱，盖上另一片面包',
      '对角切开即可',
    ],
    tags: ['早餐', '快手', '营养'],
  },
  {
    id: 8,
    name: '牛肉蔬菜卷',
    description: '高蛋白牛肉搭配新鲜蔬菜，健身后的完美补充',
    calories: 420,
    protein: 35,
    carbs: 38,
    fat: 14,
    prepTime: 20,
    difficulty: '中等',
    mealType: 'lunch',
    ingredients: [
      '牛肉片 120g',
      '全麦卷饼 1张',
      '生菜 适量',
      '洋葱 适量',
      '彩椒 适量',
      '低脂酸奶酱 1勺',
      '黑胡椒 适量',
    ],
    steps: [
      '牛肉片加黑胡椒煎熟',
      '洋葱和彩椒切丝炒软',
      '卷饼加热30秒',
      '铺上生菜、牛肉、蔬菜',
      '淋酸奶酱，卷紧即可',
    ],
    tags: ['高蛋白', '健身餐', '午餐'],
  },
  {
    id: 9,
    name: '紫薯杂粮粥',
    description: '温暖养胃的杂粮粥，富含花青素和膳食纤维',
    calories: 260,
    protein: 8,
    carbs: 52,
    fat: 2,
    prepTime: 40,
    difficulty: '简单',
    mealType: 'breakfast',
    ingredients: [
      '紫薯 1个',
      '小米 30g',
      '糙米 20g',
      '红枣 5颗',
      '枸杞 适量',
    ],
    steps: [
      '紫薯去皮切小块',
      '所有谷物提前浸泡30分钟',
      '全部材料放入锅中，加足水',
      '大火煮开后转小火熬30分钟',
      '最后加入枸杞焖5分钟',
    ],
    tags: ['早餐', '养胃', '高纤维'],
  },
  {
    id: 10,
    name: '清炒时蔬鸡丁',
    description: '色彩丰富的蔬菜炒鸡丁，营养全面又美味',
    calories: 290,
    protein: 28,
    carbs: 14,
    fat: 12,
    prepTime: 15,
    difficulty: '简单',
    mealType: 'lunch',
    ingredients: [
      '鸡胸肉 150g',
      '彩椒 1个',
      '胡萝卜 半根',
      '木耳 适量',
      '蒜 2瓣',
      '生抽 1勺',
      '淀粉 少许',
    ],
    steps: [
      '鸡胸肉切丁，加生抽和淀粉腌制',
      '蔬菜切丁备用',
      '热油滑炒鸡丁至变色盛出',
      '炒香蒜末，下蔬菜翻炒',
      '加入鸡丁，调味炒匀出锅',
    ],
    tags: ['营养均衡', '快手', '午餐'],
  },
  {
    id: 11,
    name: '酸奶水果杯',
    description: '低卡清爽的下午加餐，补充维生素和蛋白质',
    calories: 180,
    protein: 9,
    carbs: 28,
    fat: 4,
    prepTime: 5,
    difficulty: '简单',
    mealType: 'snack',
    ingredients: [
      '无糖酸奶 200g',
      '草莓 50g',
      '蓝莓 30g',
      '格兰诺拉麦片 20g',
      '蜂蜜 少许',
    ],
    steps: [
      '水果洗净切块',
      '杯中先放一层酸奶',
      '铺一层水果和麦片',
      '重复叠加，淋少许蜂蜜',
    ],
    tags: ['加餐', '低卡', '高蛋白'],
  },
  {
    id: 12,
    name: '蒜蓉蒸虾',
    description: '简单快手的高蛋白海鲜料理，鲜美低脂',
    calories: 195,
    protein: 30,
    carbs: 5,
    fat: 6,
    prepTime: 15,
    difficulty: '简单',
    mealType: 'dinner',
    ingredients: [
      '大虾 200g',
      '蒜 5瓣',
      '粉丝 30g',
      '蒸鱼豉油 1勺',
      '葱花 适量',
      '料酒 1勺',
    ],
    steps: [
      '虾开背去虾线，用料酒腌制',
      '粉丝泡软铺在盘底',
      '蒜剁成蒜蓉',
      '虾放在粉丝上，铺上蒜蓉',
      '水开蒸6分钟，淋豉油撒葱花',
    ],
    tags: ['低脂', '高蛋白', '海鲜'],
  },
];

export function getRecipesByMealType(mealType: string): Recipe[] {
  return recipes.filter((r) => r.mealType === mealType);
}

export function getRecipesByTag(tag: string): Recipe[] {
  return recipes.filter((r) => r.tags.includes(tag));
}

export function searchRecipes(query: string): Recipe[] {
  const q = query.toLowerCase();
  return recipes.filter(
    (r) =>
      r.name.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.tags.some((t) => t.toLowerCase().includes(q))
  );
}
